id = get_param(gcb,'i');
set_param(strcat(gcb,'/Desired Position'),'VariableName',strcat('Pd',id))
set_param(strcat(gcb,'/Derivative Pd'),'VariableName',strcat('dPd',id))
set_param(strcat(gcb,'/Desired Speed'),'VariableName',strcat('v_d',id))
set_param(strcat(gcb,'/Usens'),'VariableName',strcat('Usens',id))
set_param(strcat(gcb,'/gamma_i'),'VariableName',strcat('gam_i',id))
set_param(strcat(gcb,'/Gam_est'),'VariableName',strcat('Gam_est',id))
set_param(strcat(gcb,'/Sensors'),'VariableName',strcat('Sensors',id))
set_param(strcat(gcb,'/Desired Velocity'),'VariableName',strcat('U_d',id))
set_param(strcat(gcb,'/Actual Position'),'VariableName',strcat('Position',id))
set_param(strcat(gcb,'/sonar_out'),'VariableName',strcat('sonar_out',id))
set_param(strcat(gcb,'/data_out'),'VariableName',strcat('data_out',id))
set_param(strcat(gcb,'/Path-Following Controller/Path following error'),'VariableName',strcat('PFerror',id))
set_param(strcat(gcb,'/AUV/Reference Velocity'),'VariableName',strcat('Ud',id))
set_param(strcat(gcb,'/AUV/Relative Velocity'),'VariableName',strcat('U',id))
set_param(strcat(gcb,'/AUV/True Position'),'VariableName',strcat('P',id))
set_param(strcat(gcb,'/AUV/Dynamics/Propellers/Fan forces'),'VariableName',strcat('F',id))
set_param(strcat(gcb,'/AUV/Kinematics/Total Velocity'),'VariableName',strcat('Utot',id))
set_param(strcat(gcb,'/AUV/Kinematics/Vcxy'),'VariableName',strcat('Vcxy',id))
set_param(strcat(gcb,'/AUV/Kinematics/Heading'),'InitialCondition',strcat('psi0',id))
set_param(strcat(gcb,'/AUV/Kinematics/Position'),'InitialCondition',strcat('P0',id))
set_param(strcat(gcb,'/State Estimator/InitialConditionState'),'InitialCondition',strcat('State_est0',id))
set_param(strcat(gcb,'/State Estimator/InitialConditionSigma'),'InitialCondition',strcat('Sigma0',id))
set_param(strcat(gcb,'/State Estimator/Plant Cov'),'value',strcat('Q',id))
set_param(strcat(gcb,'/State Estimator/z_j'),'VariableName',strcat('z_j',id))
set_param(strcat(gcb,'/State Estimator/Estimated State'),'VariableName',strcat('State_est',id))
set_param(strcat(gcb,'/State Estimator/Covariance'),'VariableName',strcat('Sigma',id))